### ISSUE TITLE
Deployment in AWS fails even with correct creds

### ISSUE THREAD

**Issue by aktarali** [digitalrebar/core#1155]
This is the raw output from the AWS configs:
{
"region": "eu-west-1",
"vpc_id": "!default",
"provider": "AWS",
"access_key_id": "AKIAJ2GHPJD2U2TQA2URZ",
"secret_access_key": "GQv9WxElTl3QyKNPcZPQK9VjC1nMoVd3qW0wNF3V"
}

The error I am getting doesn't seem to reflect what I have configured. Errors below:
cloudwrap_1 | Registering endpoint {"region"=>"eu-west-1", "vpc_id"=>"!default", "provider"=>"AWS", "access_key_id"=>"AKIAJ2GHPJD2U2TQA2URZ", "secret_access_key"=>"GQv9WxElTl3QyKNPcZPQK9VjC1nMoVd3qW0wNF3V"} using {"admin-0"=>"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKQpM/zM47xYL8qR0cBOt0AtTO36W1E3CMxvvl49xYMQpZToBRjPYdcWBF9b3pn4mDerQXon2mR5/qFXk0oMAlQ6h/t/uHDCjrHAYVswyDZaCJPvG1U1tW1TElC001ezGRd+4GiLYlfQfZhqx73TNNjFni/Z2vGcwDuNETRWWE/h4Tf6b6YtRmKBFs3Np2e2SFIMyO1ybTyFWawR1ovmz89d3UeuKbi5dOE3h3xMxAWMW3FmadIbzgdQUAMoXjmCfmM7tRB7I4cdauPi1+FAByR+rJWN0gQpt3uiwIHpqK3/2WwYkThJDk7kRbhZzdtrjtT3X2vEDYsYo4DwsqbN5Z rebar@3fb2f44\n", "setup-0"=>"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/bk4RoTytlf0vx34+ChqFTCu5a1wgjzJToslFfTXysaqZc+AREB9PAnlchauzNFZlrk2jRPZgfYFno7LoseE4Rltn1RuYLnVkeQpmOLnaGtxKDR/tuDJl4eNG/3OyShw/F+Zl2folWDxzM73ac1Tb9/zcHd3TMi7kZlzMjWi2H+81KWHclrdVFgy1sIDeouxl0b6fs079eMrDrMND/OMUnLgmsab8dDUE1h/Du+cXqmmBRs9w2KrOeUMvUnPZ2ZSyKtTf7Puxuk2wto/v3Db4zN73WtfaEtZLiiETIGBtfQBt+5JUunjq4n+iYdyK2BcZfEo460p4Rs6q7FoaS369 ubuntu@ip-172-31-2-233\n"}
cloudwrap_1 | 
cloudwrap_1 | ==> waiter.log <==
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | 
cloudwrap_1 | ==> api.log <==
cloudwrap_1 | Creating node 2
cloudwrap_1 | Exception Create: #
cloudwrap_1 | Creating node 3
cloudwrap_1 | Exception Create: #

Could it be because of the mismatch in the field names? The names in the raw ouput do not match the error field names?

**Comment by ravolt** [comment]
This is a bug I introduced when I made vpc_id settable.  

As a workaround, you can just set your vpc_id instead of leaving it as
!default.


On 05/14/2016 03:37 AM, aktarali wrote:
>
> This is the raw output from the AWS configs:
> {
> "region": "eu-west-1",
> "vpc_id": "!default",
> "provider": "AWS",
> "access_key_id": "AKIAJ2GHPJD2U2TQA2URZ",
> "secret_access_key": "GQv9WxElTl3QyKNPcZPQK9VjC1nMoVd3qW0wNF3V"
> }
>
> The error I am getting doesn't seem to reflect what I have configured.
> Errors below:
> cloudwrap_1 | Registering endpoint {"region"=>"eu-west-1",
> "vpc_id"=>"!default", "provider"=>"AWS",
> "access_key_id"=>"AKIAJ2GHPJD2U2TQA2URZ",
> "secret_access_key"=>"GQv9WxElTl3QyKNPcZPQK9VjC1nMoVd3qW0wNF3V"} using
> {"admin-0"=>"ssh-rsa
> AAAAB3NzaC1yc2EAAAADAQABAAABAQDKQpM/zM47xYL8qR0cBOt0AtTO36W1E3CMxvvl49xYMQpZToBRjPYdcWBF9b3pn4mDerQXon2mR5/qFXk0oMAlQ6h/t/uHDCjrHAYVswyDZaCJPvG1U1tW1TElC001ezGRd+4GiLYlfQfZhqx73TNNjFni/Z2vGcwDuNETRWWE/h4Tf6b6YtRmKBFs3Np2e2SFIMyO1ybTyFWawR1ovmz89d3UeuKbi5dOE3h3xMxAWMW3FmadIbzgdQUAMoXjmCfmM7tRB7I4cdauPi1+FAByR+rJWN0gQpt3uiwIHpqK3/2WwYkThJDk7kRbhZzdtrjtT3X2vEDYsYo4DwsqbN5Z
> rebar@3fb2f44 <https://github.com/rebar/core/commit/3fb2f44>\n",
> "setup-0"=>"ssh-rsa
> AAAAB3NzaC1yc2EAAAADAQABAAABAQC/bk4RoTytlf0vx34+ChqFTCu5a1wgjzJToslFfTXysaqZc+AREB9PAnlchauzNFZlrk2jRPZgfYFno7LoseE4Rltn1RuYLnVkeQpmOLnaGtxKDR/tuDJl4eNG/3OyShw/F+Zl2folWDxzM73ac1Tb9/zcHd3TMi7kZlzMjWi2H+81KWHclrdVFgy1sIDeouxl0b6fs079eMrDrMND/OMU
> nLgmsab8dDUE1h/Du+cXqmmBRs9w2KrOeUMvUnPZ2ZSyKtTf7Puxuk2wto/v3Db4zN73WtfaEtZLiiETIGBtfQBt+5JUunjq4n+iYdyK2BcZfEo460p4Rs6q7FoaS369
> ubuntu@ip-172-31-2-233\n"}
> cloudwrap_1 |
> cloudwrap_1 | ==> waiter.log <==
> cloudwrap_1 | Finding endpoints of servers to check
> cloudwrap_1 | Finding endpoints of servers to check
> cloudwrap_1 | Finding endpoints of servers to check
> cloudwrap_1 | Finding endpoints of servers to check
> cloudwrap_1 | Finding endpoints of servers to check
> cloudwrap_1 | Finding endpoints of servers to check
> cloudwrap_1 |
> cloudwrap_1 | ==> api.log <==
> cloudwrap_1 | Creating node 2
> cloudwrap_1 | Exception Create: #
> cloudwrap_1 | Creating node 3
> cloudwrap_1 | Exception Create: #
>
> Could it be because of the mismatch in the field names? The names in
> the raw ouput do not match the error field names?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalrebar/core/issues/1155>
>

-- 

Rob
____________________________
Rob Hirschfeld, 512-773-7522

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: zehicle & ravolt

**Comment by aktarali** [comment]
Hi,

I've also tried it with adding the vpc_id as well. Same outcome.

Cheers
Ali

**Comment by zehicle** [comment]
Ali,

Thanks - that's helpful information.  I'm working on a fix for the
!default case first.

Rob

On 05/14/2016 11:40 AM, aktarali wrote:
> Hi,
>
> I've also tried it with adding the vpc_id as well. Same outcome.
>
> Cheers
> Ali
> On 14 May 2016 17:29, "Rob Hirschfeld" <notifications@github.com> wrote:
>
> > This is a bug I introduced when I made vpc_id settable.
> >
> > As a workaround, you can just set your vpc_id instead of leaving it as
> > !default.
> >
> >
> > On 05/14/2016 03:37 AM, aktarali wrote:
> > >
> > > This is the raw output from the AWS configs:
> > > {
> > > "region": "eu-west-1",
> > > "vpc_id": "!default",
> > > "provider": "AWS",
> > > "access_key_id": "AKIAJ2GHPJD2U2TQA2URZ",
> > > "secret_access_key": "GQv9WxElTl3QyKNPcZPQK9VjC1nMoVd3qW0wNF3V"
> > > }
> > >
> > > The error I am getting doesn't seem to reflect what I have configured.
> > > Errors below:
> > > cloudwrap_1 | Registering endpoint {"region"=>"eu-west-1",
> > > "vpc_id"=>"!default", "provider"=>"AWS",
> > > "access_key_id"=>"AKIAJ2GHPJD2U2TQA2URZ",
> > > "secret_access_key"=>"GQv9WxElTl3QyKNPcZPQK9VjC1nMoVd3qW0wNF3V"} using
> > > {"admin-0"=>"ssh-rsa
> > >
> >
> AAAAB3NzaC1yc2EAAAADAQABAAABAQDKQpM/zM47xYL8qR0cBOt0AtTO36W1E3CMxvvl49xYMQpZToBRjPYdcWBF9b3pn4mDerQXon2mR5/qFXk0oMAlQ6h/t/uHDCjrHAYVswyDZaCJPvG1U1tW1TElC001ezGRd+4GiLYlfQfZhqx73TNNjFni/Z2vGcwDuNETRWWE/h4Tf6b6YtRmKBFs3Np2e2SFIMyO1ybTyFWawR1ovmz89d3UeuKbi5dOE3h3xMxAWMW3FmadIbzgdQUAMoXjmCfmM7tRB7I4cdauPi1+FAByR+rJWN0gQpt3uiwIHpqK3/2WwYkThJDk7kRbhZzdtrjtT3X2vEDYsYo4DwsqbN5Z
> > > rebar@3fb2f44 <https://github.com/rebar/core/commit/3fb2f44>\n",
> > > "setup-0"=>"ssh-rsa
> > >
> >
> AAAAB3NzaC1yc2EAAAADAQABAAABAQC/bk4RoTytlf0vx34+ChqFTCu5a1wgjzJToslFfTXysaqZc+AREB9PAnlchauzNFZlrk2jRPZgfYFno7LoseE4Rltn1RuYLnVkeQpmOLnaGtxKDR/tuDJl4eNG/3OyShw/F+Zl2folWDxzM73ac1Tb9/zcHd3TMi7kZlzMjWi2H+81KWHclrdVFgy1sIDeouxl0b6fs079eMrDrMND/OMU
> > >
> >
> nLgmsab8dDUE1h/Du+cXqmmBRs9w2KrOeUMvUnPZ2ZSyKtTf7Puxuk2wto/v3Db4zN73WtfaEtZLiiETIGBtfQBt+5JUunjq4n+iYdyK2BcZfEo460p4Rs6q7FoaS369
> > > ubuntu@ip-172-31-2-233\n"}
> > > cloudwrap_1 |
> > > cloudwrap_1 | ==> waiter.log <==
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 |
> > > cloudwrap_1 | ==> api.log <==
> > > cloudwrap_1 | Creating node 2
> > > cloudwrap_1 | Exception Create: #
> > > cloudwrap_1 | Creating node 3
> > > cloudwrap_1 | Exception Create: #
> > >
> > > Could it be because of the mismatch in the field names? The names in
> > > the raw ouput do not match the error field names?
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/digitalrebar/core/issues/1155>
> > >
> >
> > --
> >
> > Rob
> > ____________________________
> > Rob Hirschfeld, 512-773-7522
> >
> > I am in CENTRAL (-6) time
> > http://robhirschfeld.com
> > twitter: @zehicle, github: zehicle & ravolt
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> >
> <https://github.com/digitalrebar/core/issues/1155#issuecomment-219229541>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalrebar/core/issues/1155#issuecomment-219230150>
>

-- 
  

Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO, Founder

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Comment by zehicle** [comment]
Check your "raw" config and remove the vpc_id from the json. 

When I'm testing the (updated) code, the ! removes the vpc from the json.

On 05/14/2016 11:40 AM, aktarali wrote:
> Hi,
>
> I've also tried it with adding the vpc_id as well. Same outcome.
>
> Cheers
> Ali
> On 14 May 2016 17:29, "Rob Hirschfeld" <notifications@github.com> wrote:
>
> > This is a bug I introduced when I made vpc_id settable.
> >
> > As a workaround, you can just set your vpc_id instead of leaving it as
> > !default.
> >
> >
> > On 05/14/2016 03:37 AM, aktarali wrote:
> > >
> > > This is the raw output from the AWS configs:
> > > {
> > > "region": "eu-west-1",
> > > "vpc_id": "!default",
> > > "provider": "AWS",
> > > "access_key_id": "AKIAJ2GHPJD2U2TQA2URZ",
> > > "secret_access_key": "GQv9WxElTl3QyKNPcZPQK9VjC1nMoVd3qW0wNF3V"
> > > }
> > >
> > > The error I am getting doesn't seem to reflect what I have configured.
> > > Errors below:
> > > cloudwrap_1 | Registering endpoint {"region"=>"eu-west-1",
> > > "vpc_id"=>"!default", "provider"=>"AWS",
> > > "access_key_id"=>"AKIAJ2GHPJD2U2TQA2URZ",
> > > "secret_access_key"=>"GQv9WxElTl3QyKNPcZPQK9VjC1nMoVd3qW0wNF3V"} using
> > > {"admin-0"=>"ssh-rsa
> > >
> >
> AAAAB3NzaC1yc2EAAAADAQABAAABAQDKQpM/zM47xYL8qR0cBOt0AtTO36W1E3CMxvvl49xYMQpZToBRjPYdcWBF9b3pn4mDerQXon2mR5/qFXk0oMAlQ6h/t/uHDCjrHAYVswyDZaCJPvG1U1tW1TElC001ezGRd+4GiLYlfQfZhqx73TNNjFni/Z2vGcwDuNETRWWE/h4Tf6b6YtRmKBFs3Np2e2SFIMyO1ybTyFWawR1ovmz89d3UeuKbi5dOE3h3xMxAWMW3FmadIbzgdQUAMoXjmCfmM7tRB7I4cdauPi1+FAByR+rJWN0gQpt3uiwIHpqK3/2WwYkThJDk7kRbhZzdtrjtT3X2vEDYsYo4DwsqbN5Z
> > > rebar@3fb2f44 <https://github.com/rebar/core/commit/3fb2f44>\n",
> > > "setup-0"=>"ssh-rsa
> > >
> >
> AAAAB3NzaC1yc2EAAAADAQABAAABAQC/bk4RoTytlf0vx34+ChqFTCu5a1wgjzJToslFfTXysaqZc+AREB9PAnlchauzNFZlrk2jRPZgfYFno7LoseE4Rltn1RuYLnVkeQpmOLnaGtxKDR/tuDJl4eNG/3OyShw/F+Zl2folWDxzM73ac1Tb9/zcHd3TMi7kZlzMjWi2H+81KWHclrdVFgy1sIDeouxl0b6fs079eMrDrMND/OMU
> > >
> >
> nLgmsab8dDUE1h/Du+cXqmmBRs9w2KrOeUMvUnPZ2ZSyKtTf7Puxuk2wto/v3Db4zN73WtfaEtZLiiETIGBtfQBt+5JUunjq4n+iYdyK2BcZfEo460p4Rs6q7FoaS369
> > > ubuntu@ip-172-31-2-233\n"}
> > > cloudwrap_1 |
> > > cloudwrap_1 | ==> waiter.log <==
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 | Finding endpoints of servers to check
> > > cloudwrap_1 |
> > > cloudwrap_1 | ==> api.log <==
> > > cloudwrap_1 | Creating node 2
> > > cloudwrap_1 | Exception Create: #
> > > cloudwrap_1 | Creating node 3
> > > cloudwrap_1 | Exception Create: #
> > >
> > > Could it be because of the mismatch in the field names? The names in
> > > the raw ouput do not match the error field names?
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/digitalrebar/core/issues/1155>
> > >
> >
> > --
> >
> > Rob
> > ____________________________
> > Rob Hirschfeld, 512-773-7522
> >
> > I am in CENTRAL (-6) time
> > http://robhirschfeld.com
> > twitter: @zehicle, github: zehicle & ravolt
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> >
> <https://github.com/digitalrebar/core/issues/1155#issuecomment-219229541>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalrebar/core/issues/1155#issuecomment-219230150>
>

-- 
  

Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO, Founder

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Comment by aktarali** [comment]
You think the ! Is being interpreted as 'not' ?

**Comment by zehicle** [comment]
@aktarali it should be fixed now.  You need to pull the latest core code and restart the rebar_api container.

The ! is a flag used to tell the system to ignore the value and not include the key when creating the json.

**Comment by aktarali** [comment]
That's great.

I'll try it out tomorrow.

Cheers
Ali.
