### ISSUE TITLE
Attribute to convert Conduit into NIC maps

### ISSUE THREAD

**Issue by ravolt** [digitalrebar/core#512]
Currently, we do all the math for conduit mapping in the network recipes and not in the core networking code.  This means we do not have access to that information as an attribute and it cannot be easily passed to downstream node roles.

We should move this math into the network modes & attributes.

@Galthaus calls this a conduit attribute table

**Comment by kathpanderson** [comment]
Based on the activity, it looks like this task has been completed and can be closed.

**Comment by galthaus** [comment]
This can be calculated for most roles now.  It still is not directly visible in the UX/UI.  I'm fine with closing it until it rears up again.
