### ISSUE TITLE
Noisy logs

### ISSUE THREAD

**Issue by sjensen** [digitalrebar/core#515]
OCB logs too many "good" status messages in the logs making it difficult to debug issues.

**Comment by cloudedge** [comment]
we need to create a catalog of them so we can reset their log level to
debug.

On Fri, Mar 27, 2015 at 7:34 AM, SCOTT JENSEN <notifications@github.com>
wrote:

> OCB logs too many "good" status messages in the logs making it difficult
> to debug issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencrowbar/core/issues/515>.
>



-- 
Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO/Founder (rob@rackn.com)

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Comment by sjensen** [comment]
it would be good to have at least three levels, error, info and debug. The debug would be I assume what is going in the log now. I assume separately you could turn on debug on Chef and get even more output, I assume this will go into another log? It would be good also if the logs were rotated. Today when I debug a problem, I move the production.log to another file and restart the OCB service to reduce the size of the file I have to look at.

**Comment by zehicle** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Rob

Confirm that you know Rob: https://www.linkedin.com/e/v2?e=0-im6czahb-ha&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=-3-bvU6M&invitationId=6118771168653701120








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im6czahb-ha&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHrM_Uz3xqEEAAAAVOo-HPxBGJCyjnIlTeatnrSBh7NnfLd6SqzCMnfZn3vBKunm5QEUPQ8uvvFTdUDjGTlo5gzJJ2AFF5hGBzq0BGZ_ZfTaoOmPuprj-8JeYNtK4GeUGwu51l9QiC24h773l39cMnjoxFuedR34gLDLGvn8zxN0a-vsg-jERoChotrBSMg0Dpk&eid=0-im6czahb-ha


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im6czahb-ha&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-wn7fnh-imfau066-5n&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=-3-bvU6M&invitationID=6118771168653701120

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=-wn7fnh-imfau066-5n&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=-3-bvU6M&invitationID=6118771168653701120





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-wn7fnh-imfau066-5n&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-wn7fnh-imfau066-5n&loid=AQE7u5j1Bbq7lAAAAVPJ-KfeH4aQ31vaTQMAbjJKeFpT-O-P6kzX7L1rnvGthR-Hf9ivyc8jGVBbt3M2d4nFWS65SVOhVcj43O-YgQymfnQiq1Tok6iSglWqh9IBVhWoI6-cMs-1XeHQ6a39d46SC2HXklqC8LS7Mn2bTn72jjzLJ6ReStFpf2U11vYXe7GAOver

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-wn7fnh-imfau066-5n&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-wn7fnh-impb4wti-c5&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=-3-bvU6M&invitationID=6118771168653701120

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=-wn7fnh-impb4wti-c5&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=-3-bvU6M&invitationID=6118771168653701120





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-wn7fnh-impb4wti-c5&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-wn7fnh-impb4wti-c5&loid=AQEraB8ZCG969QAAAVPuBMb91VHj-HJXkpLf4w-iNFRjiTtDGfXQp5q7cjCEo61HPdeOtBrZ-7YnJDp_AbAmyxP0CrAkBW25Dd55F7rvSmMhmX1NLvUGF3AlHT3HT5UwLY7hQhpY5s-iHRrwpx7EzF5VSm994qcSKFi_7tMdzjXveWwWUAa0_O-b305Gezaw_Ysp

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-wn7fnh-impb4wti-c5&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
changed to warn level
