### ISSUE TITLE
Fuel install has a Kickstart prob

### ISSUE THREAD

**Issue by sjensen** [digitalrebar/core#536]
When Installing Fuel as an OS I get an error with failing to dld the kickstart file.  A dialog on the console shows the correct path.  Clicking ok causes it to continue without an issue

**Comment by sjensen** [comment]
![image](https://cloud.githubusercontent.com/assets/1200679/7144647/e9b06708-e2b4-11e4-88e2-0c31579b88d2.png)

**Comment by sjensen** [comment]
funny looking at the screenshot it looks like the problem is that there are too many ss's in the name.

**Comment by zehicle** [comment]
not maintaining FUEL
