### ISSUE TITLE
UI System information

### ISSUE THREAD

**Issue by sjensen** [digitalrebar/core#549]
Pls add Target OS and IP addresses to the system info shown on screens.  It is difficult to tell what system is what currently.

**Comment by galthaus** [comment]
sjensen, which screens?  #574 adds it to the node screen, but I think you had something else in mind.

**Comment by kathpanderson** [comment]
I believe this issue has been resolved and can be closed. @galthaus

**Comment by galthaus** [comment]
I'll close for bookkeeping purposes.
