### ISSUE TITLE
Update the network role to remove networks

### ISSUE THREAD

**Issue by galthaus** [digitalrebar/core#595]
As part of the unmanaged update, network removal was trashed.  We should fix that.

**Comment by kathpanderson** [comment]
According to [this](http://digital-rebar.readthedocs.io/en/latest/api/api/network.html?highlight=DELETE) page of the docs, it looks like the Network API now provides a method of deleting networks. This issue can be closed, given this command still works.

**Comment by galthaus** [comment]
Closing
