### ISSUE TITLE
Destroying a role gives you the sad DR Mo

### ISSUE THREAD

**Issue by sjensen** [digitalrebar/core#615]
added a role and did not bind it to anything in a deployment.  Deleted without commiting and got the evil bunny.

corresponding error: in the prod log
2015-05-27 13:53:46.721 [21335] [FATAL] ActionController::RoutingError (No route matches [GET] "/deployment_roles/assets/ocb_logo.png"):
  actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.3) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.3) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.13) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.3) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.13) lib/rails/engine.rb:511:in `call'
  railties (4.0.13) lib/rails/application.rb:97:in `call'
  railties (4.0.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
  puma (2.11.3) lib/puma/configuration.rb:51:in `call'
  puma (2.11.3) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.3) lib/puma/server.rb:375:in `process_client'
  puma (2.11.3) lib/puma/server.rb:262:in `block in run'
  puma (2.11.3) lib/puma/thread_pool.rb:104:in `call'
  puma (2.11.3) lib/puma/thread_pool.rb:104:in `block in spawn_thread'

**Comment by StephenTames** [comment]
@galthaus Not entirely sure if this is resolved, but I am pretty sure that it has been. If you feel confident it then it can be closed.

**Comment by galthaus** [comment]
Fixed.
