### ISSUE TITLE
Error when adding host range in UI

### ISSUE THREAD

**Issue by sjensen** [digitalrebar/core#675]
Receiving a timeout error when adding a range in a network.  Refreshing the screen shows that the range did get added.

[[0;37m2015-06-23 16:56:56.840^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: calling all role on_network_change hooks for 20_Net
^[[0;37m2015-06-23 16:56:56.842^[[0m [21698] [^[[0;37mDEBUG^[[0m] ^[[1m^[[36mRole Load (1.4ms)^[[0m  ^[[1mSELECT "roles".* FROM "roles" INNER JOIN "jigs" ON "jigs"."name" = "roles"."jig_name" WHERE (jigs.active = 't') ORDER BY cohort DESC, name ASC^[[0m
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling ceph-client on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling ceph-mds on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling ceph-radosgw on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling ceph-osd on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling packstack-installed-node on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling saltstack on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling ceph-mon on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling docker-ready on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling packstack-client on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling puppet-sa on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling saltstack-minion on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling ceph-config on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling crowbar-admin-node on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling docker-prep on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling packstack-installer on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling puppet-test on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling rackn-ready on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling saltstack-master on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling sysdig on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling crowbar-installed-node on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling puppet-agent_sa on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.851^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling decommission on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling provisioner-os-install on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling raid-post-configure on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling bios-dell-rseries-configure on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling burnin-start on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling crowbar-hardware-configured on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling raid-configure on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling crowbar-managed-node on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling ipmi-configure on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling raid-discover on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling bios-discover on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling crowbar-docker-node on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling ipmi-discover on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling raid-tools-install on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling deployer-client on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling provisioner-docker-setup on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling provisioner-database on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling provisioner-repos on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling network-lldpd on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.852^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling provisioner-base-images on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.853^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling logging-client on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.853^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling provisioner-server on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.853^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling crowbar-api_server on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.853^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling crowbar-job_runner on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.853^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling dhcp-database on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.853^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling dns-bind_server on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.853^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling dns-mgmt_server on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.853^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling logging-server on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.853^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling ntp-client on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.853^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling ntp-server on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.853^[[0m [21698] [^[[32mINFO ^[[0m] NetworkRange: Calling proxy-server on_network_change for 20_Net
^[[0;37m2015-06-23 16:56:56.865^[[0m [21698] [^[[0;37mDEBUG^[[0m] ^[[1m^[[35mNodeRole Load (11.0ms)^[[0m  SELECT "node_roles".* FROM "node_roles" WHERE "node_roles"."role_id" = $1  [["role_id", 31]]
^[[0;37m2015-06-23 16:56:56.866^[[0m [21698] [^[[0;37mDEBUG^[[0m] ^[[1m^[[36m (0.2ms)^[[0m  ^[[1mBEGIN^[[0m
^[[0;37m2015-06-23 16:56:56.872^[[0m [21698] [^[[0;37mDEBUG^[[0m] ^[[1m^[[35mNodeRole Load (6.2ms)^[[0m  SELECT "node_roles".* FROM "node_roles" WHERE "node_roles"."id" = $1 LIMIT 1 FOR NO KEY UPDATE  [["id", 24]]
^[[0;37m2015-06-23 16:56:56.874^[[0m [21698] [^[[0;37mDEBUG^[[0m] ^[[1m^[[36m (1.2ms)^[[0m  ^[[1mCOMMIT^[[0m
^[[0;37m2015-06-23 16:56:56.874^[[0m [21698] [^[[0;37mDEBUG^[[0m] ^[[1m^[[35m (0.1ms)^[[0m  BEGIN
^[[0;37m2015-06-23 16:56:56.874^[[0m [21698] [^[[0;37mDEBUG^[[0m] ^[[1m^[[36m (0.1ms)^[[0m  ^[[1mSET TRANSACTION ISOLATION LEVEL READ COMMITTED^[[0m
^[[0;37m2015-06-23 16:56:56.875^[[0m [21698] [^[[0;37mDEBUG^[[0m] ^[[1m^[[35m (0.3ms)^[[0m  LOCK TABLE runs
^[[0;37m2015-06-23 16:56:56.878^[[0m [21698] [^[[0;37mDEBUG^[[0m] ^[[1m^[[36mRun Load (1.9ms)^[[0m  ^[[1mSELECT "runs".* FROM "runs" WHERE "runs"."node_role_id" = 24 AND "runs"."running" = 'f' LIMIT 1^[[0m
^[[0;37m2015-06-23 16:56:56.879^[[0m [21698] [^[[0;37mDEBUG^[[0m] ^[[1m^[[35mDeployment Load (0.2ms)^[[0m  SELECT "deployments".* FROM "deployments" WHERE "deployments"."id" = $1 LIMIT 1  [["id", 1]]
^[[0;37m2015-06-23 16:56:56.885^[[0m [21698] [^[[0;37mDEBUG^[[0m] ^[[1m^[[36mNode Load (5.3ms)^[[0m  ^[[1mSELECT "nodes".* FROM "nodes" WHERE "nodes"."id" = $1 LIMIT 1^[[0m  [["id", 2]]
^[[0;37m2015-06-23 16:56:56.886^[[0m [21990] [^[[32mINFO ^[[0m] Run: Deleting finished job 163

**Comment by StephenTames** [comment]
Someone with more expertise should look into closing this. @Meshiest

**Comment by galthaus** [comment]
not applicable.
