### ISSUE TITLE
Delete Nodes is broken

### ISSUE THREAD

**Issue by galthaus** [digitalrebar/core#911]
We can't delete nodes.  It complains about not being able to delete through the node_roles_all_pcms view.

**Comment by galthaus** [comment]
ERROR: cannot delete from view "node_role_all_pcms" DETAIL: Views containing WITH are not automatically updatable. HINT: To enable deleting from the view, provide an INSTEAD OF DELETE trigger or an unconditional ON DELETE DO INSTEAD rule.

Error Backtrace
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:641:in `prepare'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:641:in `prepare_statement'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:600:in `exec_cache'
/var/cache/rebar/gems/ruby/2.1.0/gems/schema_plus_core-0.6.0/lib/schema_plus/core/active_record/connection_adapters/postgresql_adapter.rb:33:in `block in exec_cache'
/var/cache/rebar/gems/ruby/2.1.0/gems/modware-0.1.2/lib/modware/stack.rb:55:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/modware-0.1.2/lib/modware/stack.rb:55:in `call_implementation'
/var/cache/rebar/gems/ruby/2.1.0/gems/modware-0.1.2/lib/modware/stack.rb:85:in `_modware_continue'
/var/cache/rebar/gems/ruby/2.1.0/gems/modware-0.1.2/lib/modware/stack.rb:77:in `_modware_call'
/var/cache/rebar/gems/ruby/2.1.0/gems/modware-0.1.2/lib/modware/stack.rb:83:in `_modware_continue'
/var/cache/rebar/gems/ruby/2.1.0/gems/modware-0.1.2/lib/modware/stack.rb:77:in `_modware_call'
/var/cache/rebar/gems/ruby/2.1.0/gems/modware-0.1.2/lib/modware/stack.rb:44:in `execute'
/var/cache/rebar/gems/ruby/2.1.0/gems/modware-0.1.2/lib/modware/stack.rb:20:in `start'
/var/cache/rebar/gems/ruby/2.1.0/gems/schema_monkey-2.1.3/lib/schema_monkey/stack.rb:34:in `start'
/var/cache/rebar/gems/ruby/2.1.0/gems/schema_plus_core-0.6.0/lib/schema_plus/core/active_record/connection_adapters/postgresql_adapter.rb:32:in `exec_cache'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:589:in `execute_and_clear'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:173:in `exec_delete'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:119:in `delete'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation.rb:478:in `delete_all'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/associations/has_many_association.rb:157:in `delete_count'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/associations/has_many_association.rb:164:in `delete_or_nullify_all_records'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/associations/collection_association.rb:213:in `delete_all'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/associations.rb:1705:in `destroy_associations'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/persistence.rb:170:in `destroy'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/callbacks.rb:292:in `block in destroy'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_destroy_callbacks'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/callbacks.rb:292:in `destroy'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:281:in `block in destroy'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/opt/digitalrebar/core/rails/lib/api_helper.rb:53:in `retriable_transaction'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:281:in `destroy'
/opt/digitalrebar/core/rails/app/models/node.rb:593:in `block (2 levels) in before_destroy_handler'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/delegation.rb:46:in `each'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/delegation.rb:46:in `each'
/opt/digitalrebar/core/rails/app/models/node.rb:592:in `block in before_destroy_handler'
/opt/digitalrebar/core/rails/lib/api_helper.rb:53:in `retriable_transaction'
/opt/digitalrebar/core/rails/app/models/node.rb:589:in `before_destroy_handler'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:164:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:164:in `block in halting'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `block in call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `each'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_destroy_callbacks'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/callbacks.rb:292:in `destroy'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:281:in `block in destroy'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/opt/digitalrebar/core/rails/lib/api_helper.rb:59:in `block in retriable_transaction'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/opt/digitalrebar/core/rails/lib/api_helper.rb:57:in `retriable_transaction'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:281:in `destroy'
/opt/digitalrebar/core/rails/app/controllers/nodes_controller.rb:140:in `destroy'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:313:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/var/cache/rebar/gems/ruby/2.1.0/gems/rails-observers-0.1.2/lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:455:in `public_send'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:455:in `block in make_lambda'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:312:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:312:in `block in halting'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:196:in `dispatch'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:237:in `block in action'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45:in `serve'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
/var/cache/rebar/gems/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
/var/cache/rebar/gems/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/var/cache/rebar/gems/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/query_cache.rb:36:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'
/var/cache/rebar/gems/ruby/2.1.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
/var/cache/rebar/gems/ruby/2.1.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:116:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `public_send'
/var/cache/rebar/gems/ruby/2.1.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `method_missing'
/var/cache/rebar/gems/ruby/2.1.0/gems/puma-2.14.0/lib/puma/configuration.rb:78:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request'
/var/cache/rebar/gems/ruby/2.1.0/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client'
/var/cache/rebar/gems/ruby/2.1.0/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run'
/var/cache/rebar/gems/ruby/2.1.0/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `call'
/var/cache/rebar/gems/ruby/2.1.0/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'

**Comment by zehicle** [comment]
fixed by #919
